// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLB-vn7da--F45sxJsboyJv_co7jzcdyw',
    appId: '1:102948744908:web:9865693b9bfb7385825c69',
    messagingSenderId: '102948744908',
    projectId: 'ntilearnfirebase',
    authDomain: 'ntilearnfirebase.firebaseapp.com',
    storageBucket: 'ntilearnfirebase.firebasestorage.app',
    measurementId: 'G-PYGK4GY0JB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk31OoS0_8AMQ0YiC2ze7Wz1PVk8rwtpQ',
    appId: '1:102948744908:android:411b0160b9655445825c69',
    messagingSenderId: '102948744908',
    projectId: 'ntilearnfirebase',
    storageBucket: 'ntilearnfirebase.firebasestorage.app',
  );
}
